blank_issues_enabled: true
contact_links:
  - name: Essential C Sharp Disscussions
    url: https://github.com/IntelliTect/EssentialCSharp/discussions
    about: Please ask and answer questions here.
