name: Branch v9.0 - Windows - EssentialCSharp

on:
  push:
    branches: [ v9.0 ]
  pull_request:
    branches: [ v9.0 ]
  schedule:
    - cron: 0 6 * * 1

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: v9.0
    - name: Setup dotnet 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Setup dotnet 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Get Directory
      run: pwd
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal