name: Branch v9.0 - Linux - EssentialCSharp

on:
  push:
    branches: [ v9.0 ]
  pull_request:
    branches: [ v9.0 ]
  schedule:
    - cron: 0 6 * * 1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['3.1.x', '5.0.x' ]
    steps:
    - uses: actions/checkout@v2
      with:
        ref: v9.0
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: ${{ matrix.dotnet-version }}
    - name: Get Directory
      run: pwd
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity detailed