name: Branch v9.0 - Linux - EssentialCSharp

on:
  push:
    branches: [ v9.0 ]
  pull_request:
    branches: [ v9.0 ]
  schedule:
    - cron: 0 6 * * 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: v9.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Get Directory
      run: pwd
    - name: Test
      run: dotnet test --verbosity normal