name: Test Different Locales

on:
  push:
    branches: [ v9.0 ]
  pull_request:
    branches: [ v9.0 ]
  
env:
  LOCALE_LANG: "pt_BR.UTF-8"

jobs:
  test-portuguese-locale:
    name: Test Brazilian Portuguese Locale On Ubuntu
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: | 
            3.1.x
            5.x
            6.x
      - name: Get Build Information
        run: |
          pwd
          dotnet --info
          dotnet --version
      - name: SetLocale To ${{ env.LOCALE_LANG }}, Build and Test
        run: |
          sudo locale-gen ${{ env.LOCALE_LANG }}
          sudo localectl set-locale LANG=${{ env.LOCALE_LANG }}
          LANG=${{ env.LOCALE_LANG }}
          export LANG=${{ env.LOCALE_LANG }}
          sudo update-locale LANG=${{ env.LOCALE_LANG }}
          echo Current Locale Settings:
          echo Run locale to get the information about the current locale and language settings:
          locale
          echo Run locale -a to list all enabled locales:
          locale -a
          echo Run localectl status to find system locale status.
          localectl status
          echo Visual Test
          echo "Printing date"
          date
          echo Restore dependencies
          dotnet restore
          echo Build
          dotnet build --no-restore
          echo Test
          dotnet test --no-build --no-restore --verbosity normal
