name: Sync v12.0 -> v13.0
'on':
  push:
    branches:
      - 'v12.0'
  workflow_dispatch:

concurrency:
  group: sync-v12-to-v13
  cancel-in-progress: true

jobs:
  sync_branches:
    name: Sync Branches
    runs-on: ubuntu-latest
    steps:
      - name: Keep v13.0 in sync with v12.0
        uses: jojomatik/sync-branch@v2.0.2
        with:
          source: "v12.0"
          target: "v13.0"
          strategy: "merge"
          resolve_conflicts: "false"
          git_committer_name: 'BenjaminMichaelisBot'
          git_committer_email: 'github@relay.benjamin.michaelis.net'
          github_token: ${{ secrets.GIT_PUSHTOKEN }}